### ISSUE TITLE
Unable to open a website

### ISSUE THREAD

**Issue by hadihashem** [GerHobbelt/GeckoFX-60-clone#1]
Hello
I’m using the Winform component to open a specific website: “www.youtubekids.com“
Which is actually not working as I get the following message
“To use YouTube Kids, please get a parent to update your browser.“
This website is working well using Chrome or Firefox
Can you please help me to identify where exactly does the problem come from?
Thanks and regards

**Comment by GerHobbelt** [comment]
IMPORTANT NOTE: this repo is only an archive of (by now VERY) OLD work done by Mozilla.

Any modern work should consider using either webview or CEF (or any derivative thereof).

webview: https://github.com/webview/webview
CEF: https://github.com/chromiumembedded/cef
