### ISSUE TITLE
AnyCPU support

### ISSUE THREAD

**Issue by hadihashem** [GerHobbelt/GeckoFX-60-clone#2]
Hello

Is it possible to implement a feature of AnyCPU support based on the following approach:

https://github.com/cefsharp/CefSharp/issues/1714

Regards

**Comment by GerHobbelt** [comment]
IMPORTANT NOTE: this repo is only an archive of (by now VERY) OLD work done by Mozilla.

Any modern work should consider using either webview or CEF (or any derivative thereof).

webview: https://github.com/webview/webview
CEF: https://github.com/chromiumembedded/cef
