### ISSUE TITLE
How to set device screen size?

### ISSUE THREAD

**Issue by semkken** [GerHobbelt/GeckoFX-60-clone#3]
I am trying to emulate mobile devices by setting preference "general.useragent.override".
But I can't figure out how set device screen size.
Could you please help?
Thanks

**Comment by GerHobbelt** [comment]
IMPORTANT NOTE: this repo is only an archive of (by now VERY) OLD work done by Mozilla.

Any modern work should consider using either webview or CEF (or any derivative thereof).

webview: https://github.com/webview/webview
CEF: https://github.com/chromiumembedded/cef
